// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MyMessageOptions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace My.Message {

  /// <summary>Holder for reflection information generated from MyMessageOptions.proto</summary>
  public static partial class MyMessageOptionsReflection {

    #region Descriptor
    /// <summary>File descriptor for MyMessageOptions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MyMessageOptionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZNeU1lc3NhZ2VPcHRpb25zLnByb3RvEgpNeS5NZXNzYWdlGh9nb29nbGUv",
            "cHJvdG9idWYvdGltZXN0YW1wLnByb3RvGiBnb29nbGUvcHJvdG9idWYvZGVz",
            "Y3JpcHRvci5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90byJ+ChpN",
            "eU1lc3NhZ2VEZWNsYXJhdGl2ZUZpZWxkcxIbChNwYXJ0aXRpb25fa2V5X2Zp",
            "ZWxkGAEgASgJEhYKDnNjaGVtYV92ZXJzaW9uGAIgASgJEhQKDG1lc3NhZ2Vf",
            "dHlwZRgDIAEoCRIVCg1zb3VyY2Vfc3lzdGVtGAQgASgJOmUKEmRlY2xhcmF0",
            "aXZlX2ZpZWxkcxIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxjQ",
            "hgMgASgLMiYuTXkuTWVzc2FnZS5NeU1lc3NhZ2VEZWNsYXJhdGl2ZUZpZWxk",
            "c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { MyMessageOptionsExtensions.DeclarativeFields }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::My.Message.MyMessageDeclarativeFields), global::My.Message.MyMessageDeclarativeFields.Parser, new[]{ "PartitionKeyField", "SchemaVersion", "MessageType", "SourceSystem" }, null, null, null, null)
          }));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of MyMessageOptions.proto</summary>
  public static partial class MyMessageOptionsExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::My.Message.MyMessageDeclarativeFields> DeclarativeFields =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::My.Message.MyMessageDeclarativeFields>(50000, pb::FieldCodec.ForMessage(400002, global::My.Message.MyMessageDeclarativeFields.Parser));
  }

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MyMessageDeclarativeFields : pb::IMessage<MyMessageDeclarativeFields>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MyMessageDeclarativeFields> _parser = new pb::MessageParser<MyMessageDeclarativeFields>(() => new MyMessageDeclarativeFields());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MyMessageDeclarativeFields> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::My.Message.MyMessageOptionsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyMessageDeclarativeFields() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyMessageDeclarativeFields(MyMessageDeclarativeFields other) : this() {
      partitionKeyField_ = other.partitionKeyField_;
      schemaVersion_ = other.schemaVersion_;
      messageType_ = other.messageType_;
      sourceSystem_ = other.sourceSystem_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyMessageDeclarativeFields Clone() {
      return new MyMessageDeclarativeFields(this);
    }

    /// <summary>Field number for the "partition_key_field" field.</summary>
    public const int PartitionKeyFieldFieldNumber = 1;
    private string partitionKeyField_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PartitionKeyField {
      get { return partitionKeyField_; }
      set {
        partitionKeyField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "schema_version" field.</summary>
    public const int SchemaVersionFieldNumber = 2;
    private string schemaVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SchemaVersion {
      get { return schemaVersion_; }
      set {
        schemaVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message_type" field.</summary>
    public const int MessageTypeFieldNumber = 3;
    private string messageType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageType {
      get { return messageType_; }
      set {
        messageType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "source_system" field.</summary>
    public const int SourceSystemFieldNumber = 4;
    private string sourceSystem_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SourceSystem {
      get { return sourceSystem_; }
      set {
        sourceSystem_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MyMessageDeclarativeFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MyMessageDeclarativeFields other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PartitionKeyField != other.PartitionKeyField) return false;
      if (SchemaVersion != other.SchemaVersion) return false;
      if (MessageType != other.MessageType) return false;
      if (SourceSystem != other.SourceSystem) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PartitionKeyField.Length != 0) hash ^= PartitionKeyField.GetHashCode();
      if (SchemaVersion.Length != 0) hash ^= SchemaVersion.GetHashCode();
      if (MessageType.Length != 0) hash ^= MessageType.GetHashCode();
      if (SourceSystem.Length != 0) hash ^= SourceSystem.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PartitionKeyField.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PartitionKeyField);
      }
      if (SchemaVersion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SchemaVersion);
      }
      if (MessageType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MessageType);
      }
      if (SourceSystem.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(SourceSystem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PartitionKeyField.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PartitionKeyField);
      }
      if (SchemaVersion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SchemaVersion);
      }
      if (MessageType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MessageType);
      }
      if (SourceSystem.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(SourceSystem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PartitionKeyField.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PartitionKeyField);
      }
      if (SchemaVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SchemaVersion);
      }
      if (MessageType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageType);
      }
      if (SourceSystem.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SourceSystem);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MyMessageDeclarativeFields other) {
      if (other == null) {
        return;
      }
      if (other.PartitionKeyField.Length != 0) {
        PartitionKeyField = other.PartitionKeyField;
      }
      if (other.SchemaVersion.Length != 0) {
        SchemaVersion = other.SchemaVersion;
      }
      if (other.MessageType.Length != 0) {
        MessageType = other.MessageType;
      }
      if (other.SourceSystem.Length != 0) {
        SourceSystem = other.SourceSystem;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PartitionKeyField = input.ReadString();
            break;
          }
          case 18: {
            SchemaVersion = input.ReadString();
            break;
          }
          case 26: {
            MessageType = input.ReadString();
            break;
          }
          case 34: {
            SourceSystem = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PartitionKeyField = input.ReadString();
            break;
          }
          case 18: {
            SchemaVersion = input.ReadString();
            break;
          }
          case 26: {
            MessageType = input.ReadString();
            break;
          }
          case 34: {
            SourceSystem = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
