name: Build and Test

on: 
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
  
    - name: 'ProtoBufJsonConverterTests (Debug)'
      run: dotnet test './test/ProtoBufJsonConverterTests/ProtoBufJsonConverterTests.csproj' -c Debug

    - name: 'ProtoBufJsonConverterTests (Release)'
      run: dotnet test './test/ProtoBufJsonConverterTests/ProtoBufJsonConverterTests.csproj' -c Release

    - name: 'MetadataReferenceServiceTests'
      run: dotnet test './test/MetadataReferenceServiceTests/MetadataReferenceServiceTests.csproj' -c Release